name: Tarea
description: Crear un nuevo reporte de tarea
title: '[Tarea] breve descripción'
body:
  - type: markdown
    attributes:
      value: |
        Gracias por crear una nueva tarea. Por favor completa la información necesaria.
  - type: input
    id: resumen
    attributes:
      label: Resumen de la tarea
      description: Describe brevemente de qué se trata la tarea
      placeholder: Ej: Añadir validación en el formulario de registro
    validations:
      required: true
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción detallada
      description: Explica claramente lo que se necesita hacer
      placeholder: |
        - ¿Qué se debe realizar?
        - ¿Cuál es el objetivo?
        - Información adicional relevante.
    validations:
      required: true
  - type: textarea
    id: pasos
    attributes:
      label: Pasos o subtareas (opcional)
      placeholder: |
        - Paso 1:
        - Paso 2:
        - Paso 3:
  - type: textarea
    id: notas
    attributes:
      label: Notas adicionales
      placeholder: Información extra, enlaces o comentarios
